import { prisma } from "@gcir/db";
import Link from "next/link";
import { fmtDate } from "@/lib/format";
import { GenerateBriefButton } from "./generate-brief-button";

export const dynamic = "force-dynamic";

export default async function BriefsIndex() {
  const briefs = await prisma.brief.findMany({
    orderBy: { issueNumber: "desc" },
    take: 20,
  });

  return (
    <main className="mx-auto max-w-[920px] flex-1 overflow-y-auto px-10 py-12">
      <div className="mb-2 text-[11px] font-semibold uppercase tracking-[0.08em] text-muted">
        Weekly Investor Briefs
      </div>
      <h1 className="mb-1 text-[36px] font-semibold leading-[1.1] tracking-tighter">
        Issues
      </h1>
      <p className="mb-8 text-[15.5px] text-muted-2">
        Generated by the BriefWriter agent · cleared through analyst review before send
      </p>

      <ul className="divide-y divide-line">
        {briefs.length === 0 && (
          <li className="flex flex-col items-center gap-4 py-10 text-center text-sm text-muted">
            <p>
              No briefs yet. Generate the first issue now, then keep the Monday 06:00 schedule for recurring drafts.
            </p>
            <GenerateBriefButton />
          </li>
        )}
        {briefs.map((b) => (
          <li key={b.id}>
            <Link
              href={`/briefs/${b.id}` as any}
              className="block py-5 transition-colors hover:bg-bg-2"
            >
              <div className="flex items-center justify-between gap-4">
                <div className="flex-1">
                  <div className="text-[12px] font-semibold uppercase tracking-[0.06em] text-muted">
                    Issue {b.issueNumber} · {fmtDate(b.windowStart)} – {fmtDate(b.windowEnd)}
                  </div>
                  <div className="mt-0.5 text-[18px] font-semibold leading-snug tracking-tight text-ink">
                    {b.title}
                  </div>
                </div>
                <div className="font-mono text-[11.5px] text-muted">
                  {b.publishedAt ? "published" : "draft"}
                </div>
              </div>
            </Link>
          </li>
        ))}
      </ul>
    </main>
  );
}
