import { prisma } from "@gcir/db";
import Link from "next/link";
import { ArrowUpRight, FileText, Mail } from "lucide-react";
import { fmtDate } from "@/lib/format";
import { GenerateBriefButton } from "./generate-brief-button";
import { PageHeader } from "@/components/page-header";

export const dynamic = "force-dynamic";

export default async function BriefsIndex() {
  const briefs = await prisma.brief.findMany({
    orderBy: { issueNumber: "desc" },
    take: 24,
  });

  const publishedCount = briefs.filter((b) => b.publishedAt).length;
  const latest = briefs[0];

  return (
    <main className="mx-auto max-w-[1080px] flex-1 overflow-y-auto px-10 py-12">
      <PageHeader
        sectionCode="§B"
        eyebrow="Weekly investor briefs"
        title="Issues."
        titleAccent="Mondays at 06:00 CT."
        description="Generated by the BriefWriter agent · cleared through analyst review before send. Each issue is a captain's log of the prior week — top movers, formation alerts, source health, and recommended actions across investor / developer / engineering / construction lanes."
        meta={`${briefs.length} archived`}
      />

      {/* Summary cells */}
      <section className="mb-10 grid grid-cols-2 gap-px overflow-hidden rounded-[7px] border border-line bg-line/60 sm:grid-cols-3">
        <SummaryCell value={String(briefs.length)}     label="Issues archived" />
        <SummaryCell value={String(publishedCount)}    label="Published" />
        <SummaryCell value={latest ? `#${latest.issueNumber}` : "—"} label="Latest issue" />
      </section>

      {briefs.length === 0 && (
        <div className="rounded-[7px] border border-dashed border-line bg-bone-2/40 px-6 py-16 text-center">
          <FileText className="mx-auto mb-3 h-5 w-5 text-muted" />
          <h3 className="font-display text-[24px] tracking-tight text-ink">No briefs yet</h3>
          <p className="mx-auto mt-1.5 max-w-md text-[13px] leading-relaxed text-muted">
            Generate the first issue now, then keep the Monday 06:00 schedule for recurring drafts. Each issue
            is a one-button operating brief stitched from the prior week's signals.
          </p>
          <div className="mt-6 inline-flex">
            <GenerateBriefButton />
          </div>
        </div>
      )}

      <ul className="space-y-3">
        {briefs.map((b, idx) => {
          const sourceHealth =
            b.sourceHealth &&
            typeof b.sourceHealth === "object" &&
            !Array.isArray(b.sourceHealth)
              ? (b.sourceHealth as {
                  followedWatchlists?: Array<{ name: string }>;
                  watchlistFocus?: Array<{ watchlistName: string }>;
                })
              : null;
          const linkedWatchlists = sourceHealth?.followedWatchlists?.length ?? 0;
          const focusCount = sourceHealth?.watchlistFocus?.length ?? 0;

          return (
            <li key={b.id}>
              <Link
                href={`/briefs/${b.id}` as any}
                className="group relative grid grid-cols-[80px_1fr_auto] items-center gap-6 overflow-hidden rounded-[7px] border border-line bg-bone p-5 transition-all hover:border-ink/30 hover:shadow-sm"
              >
                {/* Issue number column */}
                <div className="text-center">
                  <div className="font-display text-[44px] leading-none tracking-[-0.02em] text-ink">
                    {String(b.issueNumber).padStart(2, "0")}
                  </div>
                  <div className="mt-1 font-mono text-[9.5px] uppercase tracking-[0.20em] text-muted-2">issue</div>
                </div>

                <div className="min-w-0">
                  <div className="flex items-center gap-2 font-mono text-[10.5px] uppercase tracking-[0.14em] text-muted">
                    <span className="text-accent-ink">Window</span>
                    <span>{fmtDate(b.windowStart)} → {fmtDate(b.windowEnd)}</span>
                  </div>
                  <h2 className="mt-2 font-display text-[24px] leading-tight tracking-tight text-ink line-clamp-1">
                    {b.title}
                  </h2>
                  <div className="mt-3 flex flex-wrap items-center gap-2 text-[11.5px]">
                    <PillStat label={b.publishedAt ? "published" : "draft"} tone={b.publishedAt ? "info" : "muted"} />
                    <PillStat label={`watchlists · ${linkedWatchlists}`} />
                    <PillStat label={`focus · ${focusCount}`} />
                    {idx === 0 && <span className="rounded-[3px] border border-accent/40 bg-accent/15 px-2 py-0.5 font-mono text-[10px] font-semibold uppercase tracking-[0.12em] text-accent-ink">Latest</span>}
                  </div>
                </div>

                <div className="flex flex-col items-end gap-2">
                  <div className="font-mono text-[10.5px] uppercase tracking-[0.10em] text-muted">
                    {b.publishedAt ? fmtDate(b.publishedAt) : "unpublished"}
                  </div>
                  <span className="inline-flex items-center gap-1 font-mono text-[11px] text-muted-2 transition-all group-hover:text-accent group-hover:translate-x-0.5">
                    Open <ArrowUpRight className="h-3 w-3" />
                  </span>
                </div>
              </Link>
            </li>
          );
        })}
      </ul>

      {briefs.length > 0 && (
        <aside className="mt-10 grid grid-cols-12 gap-6 rounded-[7px] border border-line bg-bone-2/40 px-7 py-6">
          <div className="col-span-12 lg:col-span-3">
            <div className="flex items-center gap-2">
              <span className="inline-flex h-9 w-9 items-center justify-center rounded-[5px] bg-info/15 text-info">
                <Mail className="h-4 w-4" />
              </span>
              <div className="font-display text-[20px] leading-tight tracking-tight text-ink">Distribution</div>
            </div>
          </div>
          <div className="col-span-12 lg:col-span-9 text-[13.5px] leading-[1.65] text-ink-3">
            Each brief is queued through the BriefRecipient table. Plain-text rendering, unsubscribe in any issue,
            recipient logs preserved for audit. <strong className="font-medium text-ink">Generate a draft, review, then publish</strong> — the worker handles delivery.
          </div>
        </aside>
      )}
    </main>
  );
}

function SummaryCell({ value, label }: { value: string; label: string }) {
  return (
    <div className="bg-bone px-5 py-5">
      <div className="font-display text-[40px] leading-none tracking-[-0.025em] text-ink">{value}</div>
      <div className="mt-2 font-mono text-[10px] uppercase tracking-[0.18em] text-muted">{label}</div>
    </div>
  );
}

function PillStat({ label, tone = "muted" }: { label: string; tone?: "info" | "muted" }) {
  return (
    <span
      className={
        tone === "info"
          ? "rounded-[3px] border border-info/30 bg-info/10 px-2 py-0.5 font-mono text-[10px] font-medium uppercase tracking-[0.10em] text-info"
          : "rounded-[3px] border border-line bg-bone-2 px-2 py-0.5 font-mono text-[10px] font-medium uppercase tracking-[0.10em] text-muted"
      }
    >
      {label}
    </span>
  );
}
